language: node_js
sudo: false
node_js:
  - '0.12'
env:
 - TEST_DB="http://localhost:5984/testdb"
before_script:
 - npm install -g mocha pouchdb-server
 - npm install 
script: 
 - pouchdb-server -m & sleep 10s
 - mocha
